name = "activities-bot"
type = "javascript"
account_id = "f89a2a4aba44ee48a1209d9b8e172819"
workers_dev = true
zone_id = "d3197ec49346809fe08e5d9b1476e88f"
webpack_config = "webpack.config.js"
compatibility_date = "2022-02-15"
[vars]
publicKey = "906c9ed52fb5dd20ed0da9c4dc58cc46afd25a5d4c1e65ea826b2ee6bc226c06"
token = '${{ secrets.TOKEN }}'
[build]
command = "npm i -fy && npm run build"
[build.upload]
format = "service-worker"
